---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: portfolio-dev
labels:
  - includeSelectors: true
    pairs:
      variant: dev

resources:
  - ../base

images:
  - name: webclient
